# A list of devices you want to take the screenshots from
devices([
  "iPhone Xʀ"
])
 
# A list of supported languages
languages([
  'en-US',
  'zh-Hans'
])
 
# Where should the resulting screenshots be stored?
output_directory "./Screenshots"
 
# Clears previous screenshots
clear_previous_screenshots true
 
# Latest version of iOS
ios_version '12.4'

